#!/bin/sh

#
# Michael B. Kulik
#
# downloads and extracts the static ffmpeg and ffprobe
# binaries from evermeet.cx and installs them to /usr/local/bin
#

if [ $# -ne 1 ]; then
    echo "usage: $0 [version]"
    exit 1
fi

VERSION=$1

pushd /tmp &> /dev/null

# Download the binaries
if [ ! -f ffmpeg-$VERSION.7z ]; then
    curl -O http://evermeet.cx/ffmpeg/ffmpeg-$VERSION.7z
fi 

if [ ! -f ffprobe-$VERSION.7z ]; then
    curl -O http://evermeet.cx/ffprobe/ffprobe-$VERSION.7z
fi

# extract 7zip files

if [ -f ffmpeg-$VERSION.7z ]; then
    7z e ffmpeg-$VERSION.7z
fi

if [ -f ffprobe-$VERSION.7z ]; then
    7z e ffprobe-$VERSION.7z
fi

# move binaries into place
if [ -f ffmpeg ]; then
    mv ffmpeg /usr/local/bin
fi

if [ -f ffprobe ]; then
    mv ffprobe /usr/local/bin
fi

# cleanup
rm *.7z

popd &> /dev/null
